HMM:
  Train:
    En:
      train_path: "../dataset/NER/English/train.txt"
      tag_dict: {"O": 0, "B-PER": 1, "I-PER": 2, "B-ORG": 3, 
      "I-ORG": 4, "B-LOC": 5, "I-LOC": 6, "B-MISC": 7, "I-MISC": 8}
    Cn:
      train_path: "../dataset/NER/Chinese/train.txt"
      tag_dict: {'O': 0, 'B-NAME': 1, 'M-NAME': 2, 'E-NAME': 3, 
      'S-NAME': 4, 'B-CONT': 5, 'M-CONT': 6, 'E-CONT': 7, 'S-CONT': 8,
      'B-EDU': 9, 'M-EDU': 10, 'E-EDU': 11, 'S-EDU': 12, 'B-TITLE': 13, 
      'M-TITLE': 14, 'E-TITLE': 15, 'S-TITLE': 16, 'B-ORG': 17, 
      'M-ORG': 18, 'E-ORG': 19, 'S-ORG': 20, 'B-RACE': 21, 'M-RACE': 22, 
      'E-RACE': 23, 'S-RACE': 24, 'B-PRO': 25, 'M-PRO': 26, 'E-PRO': 27, 
      'S-PRO': 28, 'B-LOC': 29, 'M-LOC': 30, 'E-LOC': 31, 'S-LOC': 32}
  Val:  
    En:
      val_path: "../dataset/NER/English/validation.txt"
      out_path: "../dataset/NER/English/ans.txt"
    Cn:
      val_path: "../dataset/NER/Chinese/validation.txt"
      out_path: "../dataset/NER/Chinese/ans.txt"

  General:

  Test: # -->
    En:
      test_path: "../dataset/NER/english_test.txt"
    Cn:
      test_path: "../dataset/NER/chinese_test.txt"
